#!/bin/bash
#SBATCH --job-name=cfNIPT_watch
##SBATCH --account=[accountname]
#SBATCH --cpus-per-task=1
#SBATCH --mem=500M
#SBATCH --time=01:00:00
#SBATCH --output=logs/snakemake_watch-%j.out
#SBATCH --partition=normal

set -euo pipefail
umask 002

INTERVAL="1hour"

source "/home/$USER/miniforge3/etc/profile.d/conda.sh"

# Check if snakemake is installed
if ! conda env list | awk '{print $1}' | grep -qx snakemake_env; then
  echo "[INFO] Creating conda env 'snakemake_env'"
  conda create -y -n snakemake_env snakemake
fi

conda activate snakemake_env

echo "[INFO] Snakemake pass started at $(date)"

snakemake \
  --profile resources/slurm \
  --rerun-incomplete \
  --use-conda \
  --conda-frontend conda

echo "[INFO] Snakemake pass finished at $(date)"

# If called with --watch, resubmit itself
if [[ "${1:-}" == "--watch" ]]; then
  echo "[INFO] Scheduling next pass in $INTERVAL"
  sbatch --begin=now+${INTERVAL} "${BASH_SOURCE[0]}" --watch
fi

