# resources/slurm/config.yaml

# Snakemake core settings
snakefile: Snakefile
printshellcmds: true
keep-going: true
rerun-incomplete: true
latency-wait: 60
restart-times: 1

# Default resources Snakemake will assume if a rule doesn't override them
default-resources:
  # 15 cores
  - cpus=15
  # 32 GB RAM → 32000 MB (you can make it 32768 if you prefer power-of-two)
  - mem_mb=36000
  # optional: set a default runtime (in minutes) so SLURM jobs don’t get 0
  - runtime=180
